project_id = "dsquhilpqcwqydsfhooi"

[functions.anilist-oauth-callback]
verify_jwt = false

[functions.mal-oauth-callback]
verify_jwt = false

[functions.watchlist-sync]
verify_jwt = false

[functions.translate-text]
verify_jwt = false

[functions.vibe-check]
verify_jwt = false

[functions.ai-recommendations]
verify_jwt = false
