import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "ja" | "es" | "fr" | "de" | "pt" | "ko" | "zh";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.anime": "Anime",
    "nav.manga": "Manga",
    "nav.rankings": "Rankings",
    "nav.community": "Community",
    "nav.search": "Search",
    
    // Hero
    "hero.watchNow": "Watch Now",
    "hero.viewDetails": "View Details",
    "hero.rating": "Rating",
    "hero.airing": "Airing",
    "hero.upcoming": "Upcoming",
    
    // Sections
    "section.thisSeason": "This Season",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "Trending Now",
    "section.trendingJp": "トレンド",
    "section.popularManga": "Popular Manga",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "View All",
    "section.rankings": "Rankings",
    "section.explore": "Explore",
    
    // Coming Soon Banner
    "banner.comingSoon": "Coming Soon",
    "banner.newFeatures": "New features launching soon — stay tuned!",
    
    // CTA
    "cta.trackJourney": "Track Your Journey",
    "cta.connectDescription": "Connect your AniList or MyAnimeList account to sync your watchlist and get personalized recommendations.",
    "cta.connectAccount": "Connect Account",
    "cta.learnMore": "Learn More",
    
    // Footer
    "footer.browse": "Browse",
    "footer.connect": "Connect",
    "footer.description": "Discover your next favorite anime and manga.",
    "footer.poweredBy": "Powered by Jikan API",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.signOut": "Sign Out",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.username": "Username",
    "auth.orContinueWith": "Or continue with",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    
    // Common
    "common.episodes": "Episodes",
    "common.chapters": "Chapters",
    "common.score": "Score",
    "common.status": "Status",
    "common.genres": "Genres",
    "common.studio": "Studio",
    "common.author": "Author",
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.retry": "Retry",
    
    // Language
    "language.select": "Language",
    "language.en": "English",
    "language.ja": "Japanese",
    "language.es": "Spanish",
    "language.fr": "French",
    "language.de": "German",
    "language.pt": "Portuguese",
    "language.ko": "Korean",
    "language.zh": "Chinese",
  },
  ja: {
    // Navigation
    "nav.home": "ホーム",
    "nav.anime": "アニメ",
    "nav.manga": "マンガ",
    "nav.rankings": "ランキング",
    "nav.community": "コミュニティ",
    "nav.search": "検索",
    
    // Hero
    "hero.watchNow": "今すぐ見る",
    "hero.viewDetails": "詳細を見る",
    "hero.rating": "評価",
    "hero.airing": "放送中",
    "hero.upcoming": "放送予定",
    
    // Sections
    "section.thisSeason": "今季のアニメ",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "トレンド",
    "section.trendingJp": "トレンド",
    "section.popularManga": "人気漫画",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "すべて見る",
    "section.rankings": "ランキング",
    "section.explore": "探索",
    
    // Coming Soon Banner
    "banner.comingSoon": "近日公開",
    "banner.newFeatures": "新機能がまもなく登場 — お楽しみに！",
    
    // CTA
    "cta.trackJourney": "視聴履歴を追跡",
    "cta.connectDescription": "AniListまたはMyAnimeListアカウントを接続して、ウォッチリストを同期し、パーソナライズされたおすすめを取得しましょう。",
    "cta.connectAccount": "アカウントを接続",
    "cta.learnMore": "詳細を見る",
    
    // Footer
    "footer.browse": "ブラウズ",
    "footer.connect": "接続",
    "footer.description": "次のお気に入りのアニメとマンガを見つけましょう。",
    "footer.poweredBy": "Jikan APIを使用",
    
    // Auth
    "auth.signIn": "ログイン",
    "auth.signUp": "登録",
    "auth.signOut": "ログアウト",
    "auth.email": "メール",
    "auth.password": "パスワード",
    "auth.username": "ユーザー名",
    "auth.orContinueWith": "または続ける",
    "auth.noAccount": "アカウントをお持ちでないですか？",
    "auth.hasAccount": "すでにアカウントをお持ちですか？",
    
    // Common
    "common.episodes": "エピソード",
    "common.chapters": "章",
    "common.score": "スコア",
    "common.status": "状態",
    "common.genres": "ジャンル",
    "common.studio": "スタジオ",
    "common.author": "著者",
    "common.loading": "読み込み中...",
    "common.error": "エラー",
    "common.retry": "再試行",
    
    // Language
    "language.select": "言語",
    "language.en": "英語",
    "language.ja": "日本語",
    "language.es": "スペイン語",
    "language.fr": "フランス語",
    "language.de": "ドイツ語",
    "language.pt": "ポルトガル語",
    "language.ko": "韓国語",
    "language.zh": "中国語",
  },
  es: {
    "nav.home": "Inicio",
    "nav.anime": "Anime",
    "nav.manga": "Manga",
    "nav.rankings": "Rankings",
    "nav.community": "Comunidad",
    "nav.search": "Buscar",
    "hero.watchNow": "Ver Ahora",
    "hero.viewDetails": "Ver Detalles",
    "hero.rating": "Puntuación",
    "hero.airing": "En emisión",
    "hero.upcoming": "Próximamente",
    "section.thisSeason": "Esta Temporada",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "Tendencias",
    "section.trendingJp": "トレンド",
    "section.popularManga": "Manga Popular",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "Ver Todo",
    "section.rankings": "Rankings",
    "section.explore": "Explorar",
    "banner.comingSoon": "Próximamente",
    "banner.newFeatures": "Nuevas funciones muy pronto — ¡mantente atento!",
    "cta.trackJourney": "Sigue Tu Viaje",
    "cta.connectDescription": "Conecta tu cuenta de AniList o MyAnimeList para sincronizar tu lista y obtener recomendaciones personalizadas.",
    "cta.connectAccount": "Conectar Cuenta",
    "cta.learnMore": "Saber Más",
    "footer.browse": "Explorar",
    "footer.connect": "Conectar",
    "footer.description": "Descubre tu próximo anime y manga favorito.",
    "footer.poweredBy": "Desarrollado con Jikan API",
    "auth.signIn": "Iniciar Sesión",
    "auth.signUp": "Registrarse",
    "auth.signOut": "Cerrar Sesión",
    "auth.email": "Correo",
    "auth.password": "Contraseña",
    "auth.username": "Usuario",
    "auth.orContinueWith": "O continuar con",
    "auth.noAccount": "¿No tienes cuenta?",
    "auth.hasAccount": "¿Ya tienes cuenta?",
    "common.episodes": "Episodios",
    "common.chapters": "Capítulos",
    "common.score": "Puntuación",
    "common.status": "Estado",
    "common.genres": "Géneros",
    "common.studio": "Estudio",
    "common.author": "Autor",
    "common.loading": "Cargando...",
    "common.error": "Error",
    "common.retry": "Reintentar",
    "language.select": "Idioma",
    "language.en": "Inglés",
    "language.ja": "Japonés",
    "language.es": "Español",
    "language.fr": "Francés",
    "language.de": "Alemán",
    "language.pt": "Portugués",
    "language.ko": "Coreano",
    "language.zh": "Chino",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.anime": "Anime",
    "nav.manga": "Manga",
    "nav.rankings": "Classements",
    "nav.community": "Communauté",
    "nav.search": "Rechercher",
    "hero.watchNow": "Regarder",
    "hero.viewDetails": "Voir Détails",
    "hero.rating": "Note",
    "hero.airing": "En cours",
    "hero.upcoming": "À venir",
    "section.thisSeason": "Cette Saison",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "Tendances",
    "section.trendingJp": "トレンド",
    "section.popularManga": "Manga Populaire",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "Voir Tout",
    "section.rankings": "Classements",
    "section.explore": "Explorer",
    "banner.comingSoon": "Bientôt",
    "banner.newFeatures": "Nouvelles fonctionnalités bientôt — restez à l'écoute!",
    "cta.trackJourney": "Suivez Votre Parcours",
    "cta.connectDescription": "Connectez votre compte AniList ou MyAnimeList pour synchroniser votre liste et obtenir des recommandations personnalisées.",
    "cta.connectAccount": "Connecter Compte",
    "cta.learnMore": "En Savoir Plus",
    "footer.browse": "Parcourir",
    "footer.connect": "Connecter",
    "footer.description": "Découvrez votre prochain anime et manga préféré.",
    "footer.poweredBy": "Propulsé par Jikan API",
    "auth.signIn": "Connexion",
    "auth.signUp": "Inscription",
    "auth.signOut": "Déconnexion",
    "auth.email": "Email",
    "auth.password": "Mot de passe",
    "auth.username": "Nom d'utilisateur",
    "auth.orContinueWith": "Ou continuer avec",
    "auth.noAccount": "Pas de compte?",
    "auth.hasAccount": "Déjà un compte?",
    "common.episodes": "Épisodes",
    "common.chapters": "Chapitres",
    "common.score": "Score",
    "common.status": "Statut",
    "common.genres": "Genres",
    "common.studio": "Studio",
    "common.author": "Auteur",
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.retry": "Réessayer",
    "language.select": "Langue",
    "language.en": "Anglais",
    "language.ja": "Japonais",
    "language.es": "Espagnol",
    "language.fr": "Français",
    "language.de": "Allemand",
    "language.pt": "Portugais",
    "language.ko": "Coréen",
    "language.zh": "Chinois",
  },
  de: {
    "nav.home": "Startseite",
    "nav.anime": "Anime",
    "nav.manga": "Manga",
    "nav.rankings": "Ranglisten",
    "nav.community": "Community",
    "nav.search": "Suchen",
    "hero.watchNow": "Jetzt Ansehen",
    "hero.viewDetails": "Details",
    "hero.rating": "Bewertung",
    "hero.airing": "Laufend",
    "hero.upcoming": "Demnächst",
    "section.thisSeason": "Diese Saison",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "Trends",
    "section.trendingJp": "トレンド",
    "section.popularManga": "Beliebte Manga",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "Alle Anzeigen",
    "section.rankings": "Ranglisten",
    "section.explore": "Entdecken",
    "banner.comingSoon": "Demnächst",
    "banner.newFeatures": "Neue Funktionen kommen bald — bleiben Sie dran!",
    "cta.trackJourney": "Verfolge Deine Reise",
    "cta.connectDescription": "Verbinde dein AniList oder MyAnimeList Konto um deine Watchlist zu synchronisieren.",
    "cta.connectAccount": "Konto Verbinden",
    "cta.learnMore": "Mehr Erfahren",
    "footer.browse": "Durchsuchen",
    "footer.connect": "Verbinden",
    "footer.description": "Entdecke deinen nächsten Lieblings-Anime und Manga.",
    "footer.poweredBy": "Powered by Jikan API",
    "auth.signIn": "Anmelden",
    "auth.signUp": "Registrieren",
    "auth.signOut": "Abmelden",
    "auth.email": "E-Mail",
    "auth.password": "Passwort",
    "auth.username": "Benutzername",
    "auth.orContinueWith": "Oder fortfahren mit",
    "auth.noAccount": "Kein Konto?",
    "auth.hasAccount": "Bereits ein Konto?",
    "common.episodes": "Episoden",
    "common.chapters": "Kapitel",
    "common.score": "Bewertung",
    "common.status": "Status",
    "common.genres": "Genres",
    "common.studio": "Studio",
    "common.author": "Autor",
    "common.loading": "Laden...",
    "common.error": "Fehler",
    "common.retry": "Wiederholen",
    "language.select": "Sprache",
    "language.en": "Englisch",
    "language.ja": "Japanisch",
    "language.es": "Spanisch",
    "language.fr": "Französisch",
    "language.de": "Deutsch",
    "language.pt": "Portugiesisch",
    "language.ko": "Koreanisch",
    "language.zh": "Chinesisch",
  },
  pt: {
    "nav.home": "Início",
    "nav.anime": "Anime",
    "nav.manga": "Mangá",
    "nav.rankings": "Rankings",
    "nav.community": "Comunidade",
    "nav.search": "Buscar",
    "hero.watchNow": "Assistir",
    "hero.viewDetails": "Ver Detalhes",
    "hero.rating": "Nota",
    "hero.airing": "Em exibição",
    "hero.upcoming": "Em breve",
    "section.thisSeason": "Esta Temporada",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "Em Alta",
    "section.trendingJp": "トレンド",
    "section.popularManga": "Mangá Popular",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "Ver Tudo",
    "section.rankings": "Rankings",
    "section.explore": "Explorar",
    "banner.comingSoon": "Em Breve",
    "banner.newFeatures": "Novos recursos chegando em breve — fique ligado!",
    "cta.trackJourney": "Acompanhe Sua Jornada",
    "cta.connectDescription": "Conecte sua conta AniList ou MyAnimeList para sincronizar sua lista e receber recomendações personalizadas.",
    "cta.connectAccount": "Conectar Conta",
    "cta.learnMore": "Saiba Mais",
    "footer.browse": "Explorar",
    "footer.connect": "Conectar",
    "footer.description": "Descubra seu próximo anime e mangá favorito.",
    "footer.poweredBy": "Powered by Jikan API",
    "auth.signIn": "Entrar",
    "auth.signUp": "Cadastrar",
    "auth.signOut": "Sair",
    "auth.email": "Email",
    "auth.password": "Senha",
    "auth.username": "Usuário",
    "auth.orContinueWith": "Ou continue com",
    "auth.noAccount": "Não tem conta?",
    "auth.hasAccount": "Já tem conta?",
    "common.episodes": "Episódios",
    "common.chapters": "Capítulos",
    "common.score": "Nota",
    "common.status": "Status",
    "common.genres": "Gêneros",
    "common.studio": "Estúdio",
    "common.author": "Autor",
    "common.loading": "Carregando...",
    "common.error": "Erro",
    "common.retry": "Tentar Novamente",
    "language.select": "Idioma",
    "language.en": "Inglês",
    "language.ja": "Japonês",
    "language.es": "Espanhol",
    "language.fr": "Francês",
    "language.de": "Alemão",
    "language.pt": "Português",
    "language.ko": "Coreano",
    "language.zh": "Chinês",
  },
  ko: {
    "nav.home": "홈",
    "nav.anime": "애니메이션",
    "nav.manga": "만화",
    "nav.rankings": "순위",
    "nav.community": "커뮤니티",
    "nav.search": "검색",
    "hero.watchNow": "지금 보기",
    "hero.viewDetails": "상세 보기",
    "hero.rating": "평점",
    "hero.airing": "방영중",
    "hero.upcoming": "예정",
    "section.thisSeason": "이번 시즌",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "인기",
    "section.trendingJp": "トレンド",
    "section.popularManga": "인기 만화",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "전체 보기",
    "section.rankings": "순위",
    "section.explore": "탐색",
    "banner.comingSoon": "출시 예정",
    "banner.newFeatures": "새로운 기능이 곧 출시됩니다 — 기대해 주세요!",
    "cta.trackJourney": "시청 기록 추적",
    "cta.connectDescription": "AniList 또는 MyAnimeList 계정을 연결하여 시청 목록을 동기화하고 맞춤 추천을 받으세요.",
    "cta.connectAccount": "계정 연결",
    "cta.learnMore": "더 알아보기",
    "footer.browse": "탐색",
    "footer.connect": "연결",
    "footer.description": "당신의 다음 최애 애니메이션과 만화를 발견하세요.",
    "footer.poweredBy": "Jikan API 제공",
    "auth.signIn": "로그인",
    "auth.signUp": "회원가입",
    "auth.signOut": "로그아웃",
    "auth.email": "이메일",
    "auth.password": "비밀번호",
    "auth.username": "사용자명",
    "auth.orContinueWith": "또는 계속",
    "auth.noAccount": "계정이 없으신가요?",
    "auth.hasAccount": "이미 계정이 있으신가요?",
    "common.episodes": "에피소드",
    "common.chapters": "챕터",
    "common.score": "점수",
    "common.status": "상태",
    "common.genres": "장르",
    "common.studio": "스튜디오",
    "common.author": "작가",
    "common.loading": "로딩 중...",
    "common.error": "오류",
    "common.retry": "재시도",
    "language.select": "언어",
    "language.en": "영어",
    "language.ja": "일본어",
    "language.es": "스페인어",
    "language.fr": "프랑스어",
    "language.de": "독일어",
    "language.pt": "포르투갈어",
    "language.ko": "한국어",
    "language.zh": "중국어",
  },
  zh: {
    "nav.home": "首页",
    "nav.anime": "动漫",
    "nav.manga": "漫画",
    "nav.rankings": "排行榜",
    "nav.community": "社区",
    "nav.search": "搜索",
    "hero.watchNow": "立即观看",
    "hero.viewDetails": "查看详情",
    "hero.rating": "评分",
    "hero.airing": "播出中",
    "hero.upcoming": "即将播出",
    "section.thisSeason": "本季新番",
    "section.thisSeasonJp": "今季のアニメ",
    "section.trending": "热门",
    "section.trendingJp": "トレンド",
    "section.popularManga": "热门漫画",
    "section.popularMangaJp": "人気漫画",
    "section.viewAll": "查看全部",
    "section.rankings": "排行榜",
    "section.explore": "探索",
    "banner.comingSoon": "即将推出",
    "banner.newFeatures": "新功能即将上线 — 敬请期待！",
    "cta.trackJourney": "追踪您的旅程",
    "cta.connectDescription": "连接您的AniList或MyAnimeList账户，同步您的观看列表并获取个性化推荐。",
    "cta.connectAccount": "连接账户",
    "cta.learnMore": "了解更多",
    "footer.browse": "浏览",
    "footer.connect": "连接",
    "footer.description": "发现您下一个最爱的动漫和漫画。",
    "footer.poweredBy": "由 Jikan API 提供支持",
    "auth.signIn": "登录",
    "auth.signUp": "注册",
    "auth.signOut": "退出",
    "auth.email": "邮箱",
    "auth.password": "密码",
    "auth.username": "用户名",
    "auth.orContinueWith": "或继续使用",
    "auth.noAccount": "没有账户？",
    "auth.hasAccount": "已有账户？",
    "common.episodes": "集数",
    "common.chapters": "章节",
    "common.score": "评分",
    "common.status": "状态",
    "common.genres": "类型",
    "common.studio": "工作室",
    "common.author": "作者",
    "common.loading": "加载中...",
    "common.error": "错误",
    "common.retry": "重试",
    "language.select": "语言",
    "language.en": "英语",
    "language.ja": "日语",
    "language.es": "西班牙语",
    "language.fr": "法语",
    "language.de": "德语",
    "language.pt": "葡萄牙语",
    "language.ko": "韩语",
    "language.zh": "中文",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("bibue-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("bibue-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
